# TradingAgents-Pro output formatter
# Phase 4: Enhanced output format — produces a structured markdown report
# from the final LangGraph state.


def format_pro_report(state: dict) -> str:
    """Format the complete TradingAgents-Pro report as markdown.

    Takes the final agent state and assembles a structured report with
    executive summary, verified claims, forecasts, bias profile,
    contradictions, macro context, detailed analyst reports, and
    research debate summary.

    Args:
        state: Final LangGraph AgentState dictionary.

    Returns:
        A single markdown string containing the full report.
    """
    ticker = state.get("company_of_interest", "UNKNOWN")
    date = state.get("trade_date", "")

    sections = []

    # Title
    sections.append(f"# TradingAgents-Pro Analysis: {ticker}")
    sections.append(f"*Generated {date} | Powered by Polaris Knowledge API*\n")

    # Executive Summary (extracted from final_trade_decision)
    decision = state.get("final_trade_decision", "")
    sections.append("---")
    sections.append(decision)

    # Fact Check Report
    fact_check = state.get("fact_check_report", "")
    if fact_check:
        sections.append("\n---\n## Verified Claims")
        sections.append(fact_check)

    # Forecast
    forecast = state.get("forecast_report", "")
    if forecast:
        sections.append("\n---\n## Forward Outlook")
        sections.append(forecast)

    # Bias Profile
    bias = state.get("bias_report", "")
    if bias:
        sections.append("\n---\n## Bias Profile")
        sections.append(bias)

    # Contradictions
    contradictions = state.get("contradiction_report", "")
    if contradictions:
        sections.append("\n---\n## Contradictions & Data Consistency")
        sections.append(contradictions)

    # Macro Context
    macro = state.get("macro_report", "")
    if macro:
        sections.append("\n---\n## Macro Context")
        sections.append(macro)

    # Analyst Reports
    sections.append("\n---\n## Detailed Analyst Reports")

    for name, key in [
        ("Market Analysis", "market_report"),
        ("Sentiment Analysis", "sentiment_report"),
        ("News Analysis", "news_report"),
        ("Fundamentals Analysis", "fundamentals_report"),
    ]:
        report = state.get(key, "")
        if report:
            sections.append(f"\n### {name}")
            sections.append(report)

    # Research Debate
    debate = state.get("investment_plan", "")
    if debate:
        sections.append("\n---\n## Research Debate Summary")
        sections.append(debate)

    # Footer
    sections.append("\n---")
    sections.append(
        "*This report was generated by TradingAgents-Pro, an enhanced multi-agent trading framework.*"
    )
    sections.append(
        "*Data provided by [Polaris Knowledge API](https://thepolarisreport.com) "
        "-- verified intelligence from premium major sources.*"
    )
    sections.append(
        "\n*This is not financial advice. Past performance does not guarantee future results.*"
    )

    return "\n\n".join(sections)
